In [1]:
# :! Isareti Kullanacagim Code Parcalari

In [2]:
import numpy as np # numpy Kutuphanesini Import etme

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

print("Carpimlari : ",a*b)

Carpimlari :  [ 5 12 21 32 45]


In [3]:
c = np.array([1,4,5,6,7])

d = np.array([5])

print("Carpimlari : ",c*d)

Carpimlari :  [ 5 20 25 30 35]


In [4]:
e = np.array([1, 2.8, 3, 4, 5], dtype = "float") # array ler bir tip oldugu icin tip atamasi da yapabiliyoruz.

print(e)

[1.  2.8 3.  4.  5. ]


In [5]:
e = np.array([1.9, 2.8, 3.7, 4.1, 5.6], dtype = "int")

print(e)

[1 2 3 4 5]


In [6]:
# Array ler de Cok Boyutlu Dizi Tanimlamasi


print(np.zeros(10, dtype = int)) # 10 tane int tipinde 0 olusturduk

[0 0 0 0 0 0 0 0 0 0]


In [7]:
print(np.ones((3,5))) # 3 e 5 lik float tipinde 1 bulunan matris olusturduk

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# Eger Belli Bir Sayi dan Olusmasini Istiyorsak;

print(np.full((3,5),8)) # 3 e 5 lik 8 bulunan dizi

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [9]:
# :!
print(np.arange(0, 30, 4)) # Sifirdan 30 a 4 er 4 er artan dizi

[ 0  4  8 12 16 20 24 28]


In [10]:
print(np.linspace(0,1,10)) # 0 ile 1 arasinda 10 tane deger olustur dedik

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [11]:
# Ortalamasi ve Standart Sapmasini Bizim Belirttigimiz Fonksiyon
# Istatistik
# :!

print(np.random.normal(10, 4, (3,4))) # Ortalamasi 10 , standart sapmasi 4 olan , 3'e 4 luk random veren matris

[[15.56834811 -0.18058298 15.31322232 12.28485698]
 [ 6.11380615  5.81213276  9.07759132  6.4327303 ]
 [ 9.64262416 17.17613232 12.31090797  9.45093001]]


In [12]:
# :!
print(np.random.randint(0, 10, (3,5)))

[[4 4 4 7 2]
 [8 7 1 2 3]
 [2 0 7 5 0]]
