In [1]:
# PANDAS KUTUPHANESI'ni import Ediyoruz

import pandas as pd

In [2]:
Seri = pd.Series([10,7,8,3,5,4]) # Series Ifadesinin Ilk Harfi Buyuk Yazilir.

print(Seri)

0    10
1     7
2     8
3     3
4     5
5     4
dtype: int64


In [3]:
print(type(Seri)) # Burada da Gorulecegi Uzere Bu Ifade Seri'dir.

<class 'pandas.core.series.Series'>


In [4]:
print(Seri.axes) # Bu Serinin Index Bilgilerine Ulasiyoruz ------> Bu Serinin Indexleri 0 Dan Baslayip, 6 ya kadar gidiyor ve 1 er 1 er artmaktadir.

[RangeIndex(start=0, stop=6, step=1)]


In [5]:
print(Seri.dtype) # Serinin Icerisindeki Elemanlarin Tip Bilgisinin Ne Oldugunu Ogreniyoruz.

int64


In [6]:
print(Seri.size) # Icerisindeki Eleman Sayisi

6


In [7]:
print(Seri.ndim) # Serinin Kac Boyutlu Oldugunu Ogreniyoruz.

1


In [8]:
print(Seri.values) # Sadece Bir Array Gibi veya Liste gibi Ulasmak Istersek Bunu Kullanabiliriz.

[10  7  8  3  5  4]


In [9]:
print(Seri.head()) # Bu Ifade Ile Serimizin Ilk "5" Gozdeki Elemanlarina Ve Bunlarin Indek Numaralarina Erisebiliyoruz.

0    10
1     7
2     8
3     3
4     5
dtype: int64


In [10]:
print(Seri.head(3)) # Bu Ifade Ile Serimizin Ilk "3" Gozdeki Elemanlarina Ve Bunlarin Indek Numaralarina Erisebiliyoruz.

0    10
1     7
2     8
dtype: int64


In [11]:
print(Seri.tail()) # Bu Ifade Ile Serimizin Son "5" Gozdeki Elemanlarina Ve Bunlarin Indek Numaralarina Erisebiliyoruz.

1    7
2    8
3    3
4    5
5    4
dtype: int64


In [12]:
print(Seri.tail(3)) # Bu Ifade Ile Serimizin Son "3" Gozdeki Elemanlarina Ve Bunlarin Indek Numaralarina Erisebiliyoruz.

3    3
4    5
5    4
dtype: int64


In [13]:
Seri_1 = pd.Series([44,88,95,7,1,3,41])

print(Seri_1) # Normal Sartlarda Indek Numaralari 0 dan Baslayarak Eleman Sayisi Kadar Artarak Devam Eder Lakin Biz Index Numaralarini Kendimiz Ayarlayabiliyoruz.

0    44
1    88
2    95
3     7
4     1
5     3
6    41
dtype: int64


In [14]:
# Index Numarasi Belirleme

Seri_2 = pd.Series([21,64,9,7,82,33,43,71,42] , index = [1,3,5,7,9,11,13,15,17])

print(Seri_2) # Istedigimiz Index Numarasina Gore Atama Yaptik

1     21
3     64
5      9
7      7
9     82
11    33
13    43
15    71
17    42
dtype: int64


In [15]:
# Index Numarasi Belirleme ( "String"  Ifade Ile)

Seri_2 = pd.Series([21,64,9,7,82,33,43,71,42] , index = ["A","B","c","d","e","f","G","h","i"]) # Buyuk Kucuk Harf'e Gore Atama Yapabiliyoruz.

print(Seri_2) # Istedigimiz Index Numarasina Gore Atama Yaptik

A    21
B    64
c     9
d     7
e    82
f    33
G    43
h    71
i    42
dtype: int64


In [16]:
#**************************************************************************************************************************************************************
#**************************************************************************************************************************************************************
# BURAYA BIR BAK "D" HARFI NIYE DAHIL ? 
#**************************************************************************************************************************************************************
#**************************************************************************************************************************************************************

print(Seri_2["A":"d"])

A    21
B    64
c     9
d     7
dtype: int64


In [17]:
# Sozluk Uzerinden Liste Olusturmak

Sozluk = {"Canakkale" : 17, "Istanbul" : 34, "Tekirdag": 59, "Izmir" : 35}

Seri_3 = pd.Series(Sozluk)

print(Seri_3)

Canakkale    17
Istanbul     34
Tekirdag     59
Izmir        35
dtype: int64


In [18]:
# Iki Seriyi Birlestirerek Bir Seri Olusturma

Seri_4 = pd.concat([Seri_1 , Seri_2])

print(Seri_4)

0    44
1    88
2    95
3     7
4     1
5     3
6    41
A    21
B    64
c     9
d     7
e    82
f    33
G    43
h    71
i    42
dtype: int64


In [19]:
import numpy as np

Text_1 = np.array([17,442,13,47,65])

Seri_5 = pd.Series(Text_1)

print(Seri_5)

0     17
1    442
2     13
3     47
4     65
dtype: int64


In [20]:
print(Seri_5[2])

print("\n********\n")

print(Seri_5[2:5])

13

********

2    13
3    47
4    65
dtype: int64


In [21]:
# !!! Soo Important !!!

Seri_6 = pd.Series([22,64,84,41],
                   index = ["reg","loj","cart","rf"])

print(Seri_6.index)

print("\n****************************************************\n")

print(Seri_6.keys)

print("\n****************************************************\n")

print(list(Seri_6.items()))

print("\n****************************************************\n")

print(Seri_6.values)

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

****************************************************

<bound method Series.keys of reg     22
loj     64
cart    84
rf      41
dtype: int64>

****************************************************

[('reg', 22), ('loj', 64), ('cart', 84), ('rf', 41)]

****************************************************

[22 64 84 41]


In [22]:
# Sorgulama Islemleri

print("reg" in Seri_6) # reg Ifadesi Seri_6 nin Icerisinde mi ?

print("\n*****\n")

print("Ahmet" in Seri_6) # Ahmet Ifadesi Seri_6 nin Icerisinde mi ?

True

*****

False


In [23]:
print(Seri_6["reg"]) # Normal Bir Sekilde Index Numarasina Gore Veriye Ulasma

print("\n*****\n")

print(Seri_6[["reg" , "rf"]]) # Fancy Index Ile Veriye Ulasma Kullanilmistir.

print("\n*****\n")

Seri_6["reg"] = "Bilal"

print(Seri_6["reg"]) # Serimizdeki Bir Ifadeyi Index Numarasina Gore Degistirebiliyoruz.

22

*****

reg    22
rf     41
dtype: int64

*****

Bilal


In [24]:
print(Seri_6["reg":"loj"]) # DİKKAT   ---------->   "loj" Ifadesini de Aldi 

reg    Bilal
loj       64
dtype: object


In [25]:
# !!! Soo Important !!!

# Pandas DataFrame Olusturma

List_1 = [1,54,96,85,72,34]

Data_Frame_1 = pd.DataFrame(List_1 , columns = ["Degisken Ismi"]) # Burada 1. Goz Kismina Listeyi , 2. Goz Kismina DataFrame'nin Ismini Yaziyoruz.

print(Data_Frame_1)

   Degisken Ismi
0              1
1             54
2             96
3             85
4             72
5             34


In [26]:
# 2 boyutlu DataFrame Olusturma

List_2 = np.arange(1,10).reshape((3,3)) # Listemizi Olusturduk

print(List_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
Data_Frame_2 = pd.DataFrame(List_2, columns = ["Var1", "Var2", "Var3"]) # 2 Boyutlu DataFrame Olusturduk.

print(Data_Frame_2)

   Var1  Var2  Var3
0     1     2     3
1     4     5     6
2     7     8     9


In [28]:
Data_Frame_2.head() # Bastan Ilk 5 Elemani Gosteriyordu.

Var1  Var2  Var3
0     1     2     3
1     4     5     6
2     7     8     9

In [29]:
Data_Frame_2.tail(2) # Sondan Ilk 2 Elemani Gosteriyordu.

Var1  Var2  Var3
1     4     5     6
2     7     8     9

In [30]:
print(Data_Frame_2.columns) # Degiskenlerin Isimlerini Getirir

Index(['Var1', 'Var2', 'Var3'], dtype='object')


In [31]:
# Degisken Isimlerini De Degistirebiliriz

Data_Frame_2.columns = ("deg1", "deg2", "deg3") # Degisken Isimlerini Degistirdik.

print(Data_Frame_2)

   deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9


In [32]:
print(type(Data_Frame_2)) # degiskenin Tipinin DataFrame Oldugunu Goruyoruz

<class 'pandas.core.frame.DataFrame'>


In [33]:
print(Data_Frame_2.axes) # Satir Ve Sutun Bilgilerini Bize Verir. -------->   Indexlerin 0 dan baslayarak 3 e kadar 1 er 1 er arttigini ve Degisken Isimlerini Verir.

[RangeIndex(start=0, stop=3, step=1), Index(['deg1', 'deg2', 'deg3'], dtype='object')]


In [34]:
print(Data_Frame_2.shape) # Data_Frame_2 Ifadesinin Boyut Bilgisini Bize Gosterir

(3, 3)


In [35]:
print(Data_Frame_2.ndim) # Data_Frame_2 Ifadesinin Kac Boyutlu Oldugunu Bize Gosterir

2


In [36]:
print(Data_Frame_2.size) # Data_Frame_2 Ifadesinin Eleman Sayisini Bize Gosterir

9


In [37]:
# !!! Soo Important !!!

#   "Data_Frame_2"   Ifadesi Normalde Veri Tipi Olarak "DataFrame" dir fakat Sadece Degerleri Gormek Istersek Array Formatina Ceviriyor.

print(Data_Frame_2.values) # sadece Degerlerine Ulasmak Icin Kullanilir. 

print("\n**********\n")

print(type(Data_Frame_2.values)) # Array Formatinda Oldugunu Gorduk

[[1 2 3]
 [4 5 6]
 [7 8 9]]

**********

<class 'numpy.ndarray'>


In [38]:
List_3 = np.arange(1,11) # Listemizi Olusturduk

Data_Frame_3 = pd.DataFrame(List_3 , columns = ["Degerler"])

print(Data_Frame_3)

   Degerler
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10


In [39]:
# !! Soo Important !!

# Eger DataFrame'lerde Index'lerden Alinan Bilgi [0:3] ise 0 dan 3 e kadar (3 dahil degil), Alinan Bilgi ["A" : "E"] ise "A" dan "E" ye kadar (E dahil'dir)

In [40]:
Liste_4 = np.random.randint(10, size = 5)
Liste_5 = np.random.randint(10, size = 5)
Liste_6 = np.random.randint(10, size = 5)

In [41]:
Sozluk_1 = {"Var_1":Liste_4, "Var_2":Liste_5, "Var_3":Liste_6}

In [42]:
Sozluk_1

{'Var_1': array([3, 2, 4, 7, 6]),
 'Var_2': array([0, 7, 5, 2, 2]),
 'Var_3': array([1, 6, 2, 0, 5])}

In [43]:
Data_Frame_3 = pd.DataFrame(Sozluk_1)

In [44]:
Data_Frame_3

Var_1  Var_2  Var_3
0      3      0      1
1      2      7      6
2      4      5      2
3      7      2      0
4      6      2      5

In [45]:
Liste_7 = np.arange(1,10).reshape(3,3)

Data_Frame_4 = pd.DataFrame(Liste_7, columns = ["Var_1", "Var_2", "Var_3"])

In [46]:
Data_Frame_4

Var_1  Var_2  Var_3
0      1      2      3
1      4      5      6
2      7      8      9

In [47]:
Data_Frame_3.index = ("a", "b", "c", "d", "e")

In [48]:
Data_Frame_3

Var_1  Var_2  Var_3
a      3      0      1
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [49]:
# DataFrame'lerden Eleman Silme Islemi

Data_Frame_3.drop("a", axis = 0) # Eleman Silinmis Gibi Duruyo ama "Data_Frame_3" Adli Ifadeyi Yazdirmaya Kalksak Silinmedigini Goruruz (Gorelim)(Asagida)

Var_1  Var_2  Var_3
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [50]:
Data_Frame_3 # Silinmedigini Gorduk "a" Index'inin

Var_1  Var_2  Var_3
a      3      0      1
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [51]:
# Kalici Olarak Silmek Istersek "inplace" Diye Bir Code Kullanmamız Lazim

Data_Frame_3.drop("a", axis = 0, inplace = True)

In [52]:
Data_Frame_3 # Goruldugu Uzere Silinme Islemi Basari Ile Gerceklesti.

Var_1  Var_2  Var_3
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [53]:
# Fancy Index Ile Eleman Silme Islemi

Liste_8 = ["c", "e"]

Data_Frame_3.drop(Liste_8, axis = 0)

Var_1  Var_2  Var_3
b      2      7      6
d      7      2      0

In [54]:
# Ara Bi Not:

Data_Frame_3

Var_1  Var_2  Var_3
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [55]:
"Var_1" in Data_Frame_3 #    "Var_1"    Ifadesi     "Data_Frame_3"      Ifadesinin Icerisinde Var mi?

True

In [56]:
"b" in Data_Frame_3 #    "b"    Ifadesi     "Data_Frame_3"      Ifadesinin Icerisinde Var mi?  -------->> Yok Cunku "b" Indextir.

False

In [57]:
Liste_9 = ["Var_1", "Var_4", "Var_2"]

for i in Liste_9:
    print(i in Data_Frame_3)

True
False
True


In [58]:
Data_Frame_3

Var_1  Var_2  Var_3
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [59]:
# "Var_1" ve "Var_2" Kullanarak "Var_4" Adinda Bir Sutun Olusturma Islemi

Data_Frame_3["Var_4"] = Data_Frame_3["Var_1"] + Data_Frame_3["Var_2"]

In [60]:
Data_Frame_3

Var_1  Var_2  Var_3  Var_4
b      2      7      6      9
c      4      5      2      9
d      7      2      0      9
e      6      2      5      8

In [61]:
# Sutun Bazinda Silme Islemi

Data_Frame_3.drop("Var_4", axis = 1) # inplace Kullanmadigimiz Icin Silme Islemi Original Halinde Yapilmaz

Var_1  Var_2  Var_3
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [62]:
Data_Frame_3 # Silinmedigini Gorduk

Var_1  Var_2  Var_3  Var_4
b      2      7      6      9
c      4      5      2      9
d      7      2      0      9
e      6      2      5      8

In [63]:
Data_Frame_3.drop("Var_4", axis = 1, inplace = True) # Kalici Olarak Silme Komutu Verdik

In [64]:
Data_Frame_3

Var_1  Var_2  Var_3
b      2      7      6
c      4      5      2
d      7      2      0
e      6      2      5

In [65]:
# Fancy Index Ile Silme Islemi (Sutun Bazinda)

Liste_10 = ["Var_1", "Var_2"]

Data_Frame_3.drop(Liste_10, axis = 1)

Var_3
b      6
c      2
d      0
e      5

In [66]:
Liste_11 = np.random.randint(1,10, size = (10,3))

Data_Frame_4 = pd.DataFrame(Liste_11, columns = ["Var1", "Var2", "Var3"])

In [67]:
Data_Frame_4

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3
3     8     9     1
4     4     8     1
5     8     4     9
6     3     6     4
7     7     9     5
8     6     6     6
9     1     3     8

In [68]:
# Python Data_Framelerinde En Cok Yapilan Hatalar ---> Liste, Array,... Icerisinde Elemanlara Ulasma Islemi

Data_Frame_4.loc[0:3] #    "loc"   Fonksiyonunda Son Eleman Dahil Olur ( Koseli Parantez Icinde Ne Goruyorsan Onu Alirsin )

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3
3     8     9     1

In [69]:
Data_Frame_4.iloc[0:3] #    "iloc"   Fonksiyonunda Bilinen Liste Mantigi Ile Calisir Son Eleman Dahil Degildir ( Listelerde Index Mantigi Vardir)

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3

In [70]:
Data_Frame_4

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3
3     8     9     1
4     4     8     1
5     8     4     9
6     3     6     4
7     7     9     5
8     6     6     6
9     1     3     8

In [71]:
Data_Frame_4.loc[0:3, "Var3"] # Sag tarafa "Var3" Yazma Islemi ( yani Belli Bir Degiskene Ulasma Islemi Yapmak Icin ) ".loc" Fonksiyonu Ile Yapilir ( ".iloc"  Ile Yapilmaz) 

0    3
1    3
2    3
3    1
Name: Var3, dtype: int64

In [72]:
# ".iloc" Ile Belli Bir Degiskene Su Sekilde Ulasabiliriz

Data_Frame_4.iloc[0:3]["Var3"] # Fakat ".iloc" Ile ".loc" Arasindaki Index Secme Islemleri Farkli Oldugu Icin Usttekinden Farkli Cikti

0    3
1    3
2    3
Name: Var3, dtype: int64

In [73]:
# DataFrame Icerinden Bir Degisken Secme

Data_Frame_4["Var1"]

0    8
1    9
2    7
3    8
4    4
5    8
6    3
7    7
8    6
9    1
Name: Var1, dtype: int64

In [74]:
# DataFrame De Bir Degisken Icerisinde Gozlem Birimi Araligi Secme

Data_Frame_4["Var1"][0:3]

0    8
1    9
2    7
Name: Var1, dtype: int64

In [75]:
# Farkli Bir Sekilde Ulasma
Data_Frame_4[0:3]["Var1"]

0    8
1    9
2    7
Name: Var1, dtype: int64

In [76]:
# Bu Sekilde Hata Verir ( Birden Fazla Degikene Ulasmak Istersek Fancy Index Yardimi Ile Ulasmamiz Lazim )
# Data_Frame_4[0:3]["Var1","Var2"]  HATA VERIR

Data_Frame_4[["Var1", "Var2"]] #   "DIKKAT"   Iki Tane Koseli Parantez Var  ------  Fancy Index Ile Ulastik

Var1  Var2
0     8     5
1     9     2
2     7     1
3     8     9
4     4     8
5     8     4
6     3     6
7     7     9
8     6     6
9     1     3

In [77]:
# Verilere Farkli Bir Sekilde Ulasma Stilleri

Data_Frame_4[0:4][["Var1", "Var2"]]

Var1  Var2
0     8     5
1     9     2
2     7     1
3     8     9

In [78]:
Liste_12 = ["Var1", "Var2"]

Data_Frame_4[Liste_12]  #  Fancy Index Ile Ulastik

Var1  Var2
0     8     5
1     9     2
2     7     1
3     8     9
4     4     8
5     8     4
6     3     6
7     7     9
8     6     6
9     1     3

In [79]:
# Farkli Bir Sekilde Ulasma Stili
Data_Frame_4[0:3]

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3

In [80]:
# Farkli Bir Sekilde Ulasma Stili

Data_Frame_4.Var1

0    8
1    9
2    7
3    8
4    4
5    8
6    3
7    7
8    6
9    1
Name: Var1, dtype: int64

In [81]:
Data_Frame_4[Data_Frame_4.Var1>5] # Data_Frame_4  Icerisindenki "Var1" Adli Degiskenin Ogeleri Arasindan 5'ten Buyuk Olanlari Aldi ( Yatayda Index Numarasina Gore aliyor)
# Beraberinde Diger Degiskenlerin Ogeleri de Geldi ( Index Numarasina Gore Aldigi Icin )

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3
3     8     9     1
5     8     4     9
7     7     9     5
8     6     6     6

In [82]:
Data_Frame_4[Data_Frame_4.Var1>5] # Burasi Bir DataFramedir

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3
3     8     9     1
5     8     4     9
7     7     9     5
8     6     6     6

In [83]:
Data_Frame_4[Data_Frame_4.Var1>5]["Var1"] # Bu DataFrame Icerisinden "Var1" Degiskeni Sectik ( Birden Fazla Degisken'de Secebilirdik)

0    8
1    9
2    7
3    8
5    8
7    7
8    6
Name: Var1, dtype: int64

In [84]:
# Yukarida DataFrame Icin Bir Kosul Koyduk, Birden Fazla Kosul Da Koyabiliriz

Data_Frame_4[(Data_Frame_4.Var3 < 6) & (Data_Frame_4.Var3 > 3)] # Ayni Degisken Uzerinde Yapmak Zorunda Degiliz Asagida Ona Ornek Verelim

Var1  Var2  Var3
6     3     6     4
7     7     9     5

In [85]:
Data_Frame_4[(Data_Frame_4.Var1 >3) & (Data_Frame_4.Var3 < 8)] # Iki Farkli Degisken Uzerinde Iki Farkli Kosul Islemi Uyguladik

Var1  Var2  Var3
0     8     5     3
1     9     2     3
2     7     1     3
3     8     9     1
4     4     8     1
7     7     9     5
8     6     6     6

In [86]:
# Data_Frame_4[(Data_Frame_4.Var1 > 15), ["Var1", "Var2"]]   HATA ALIRIZ (   ".loc"    Ifadesi Eklenmesi Lazim)

Data_Frame_4.loc[(Data_Frame_4.Var1 > 3), ["Var1", "Var2"]]

Var1  Var2
0     8     5
1     9     2
2     7     1
3     8     9
4     4     8
5     8     4
7     7     9
8     6     6

In [87]:
# Farkli Bir Sekilde   ".loc"   Ifadesi Kullanmadan da Yapabiliriz

Data_Frame_4[Data_Frame_4.Var1 > 3]["Var1"]

0    8
1    9
2    7
3    8
4    4
5    8
7    7
8    6
Name: Var1, dtype: int64

In [88]:
# Farkli Bir Sekilde

Data_Frame_4[Data_Frame_4.Var1 > 3][["Var1","Var2"]] # Birden Cok Degisken Koyacaksak Iki Tane Koseli Parantez Koymamiz Lazim

Var1  Var2
0     8     5
1     9     2
2     7     1
3     8     9
4     4     8
5     8     4
7     7     9
8     6     6

In [89]:
Liste_13 = np.random.randint(1,30, size = (5,3))

Data_Frame_5 = pd.DataFrame(Liste_13, columns = ["Deg_1", "Deg_2", "Deg_3"])

In [90]:
Data_Frame_5

Deg_1  Deg_2  Deg_3
0      8     13      3
1     13     21     14
2      1      2      1
3      4      5     16
4     22     18     23

In [91]:
# DataFrame Deki Tum Elemenalara Sayi Ekleme Islemi

Data_Frame_6 = Data_Frame_5 + 100

In [92]:
Data_Frame_6

Deg_1  Deg_2  Deg_3
0    108    113    103
1    113    121    114
2    101    102    101
3    104    105    116
4    122    118    123

In [93]:
# DataFrame Birlestirme Islemleri

pd.concat([Data_Frame_5, Data_Frame_6]) # Burada Indexler De Sikinti Cikti Bunu Nasil Cozeriz

Deg_1  Deg_2  Deg_3
0      8     13      3
1     13     21     14
2      1      2      1
3      4      5     16
4     22     18     23
0    108    113    103
1    113    121    114
2    101    102    101
3    104    105    116
4    122    118    123

In [94]:
# Kullandigimiz Fonksiyonun Index Ayarinin Varsayilan Ayarlarina Bakiyoruz

?pd.concat

# ignore_index: = False         ----------->> Varsayilan Ayarin Bu Oldugunu Gorduk ( Bunu Degistiricez )

In [95]:
pd.concat([Data_Frame_5, Data_Frame_6], ignore_index = True) # Goruldugu Uzere Sorun Cozuldu ( Index Numaralari Normale Dondu ) ( NOT: IKI ALT TARAFTA BURAYI ANLATIYORUM )

Deg_1  Deg_2  Deg_3
0      8     13      3
1     13     21     14
2      1      2      1
3      4      5     16
4     22     18     23
5    108    113    103
6    113    121    114
7    101    102    101
8    104    105    116
9    122    118    123

In [96]:
# Bu Data Frame'nin Degiskenlerine Ulasma (Bunu Zaten Biliyoruz ( Tekrar Olsun :) ) !! Onemli Bir Seye Dikkat Cekicem.

Data_Frame_5.columns

Index(['Deg_1', 'Deg_2', 'Deg_3'], dtype='object')

In [97]:
Data_Frame_6.columns

Index(['Deg_1', 'Deg_2', 'Deg_3'], dtype='object')

In [98]:
# IKI UST TARAFTAKI YERI ANLATIYORUM (not biraktigim yer)

pd.concat([Data_Frame_5, Data_Frame_6]) # Bu Birlestirme Islemi Degisken Isimleri Ayni Oldugu Icin Sorunsuz Bi Sekilde Oldu

Deg_1  Deg_2  Deg_3
0      8     13      3
1     13     21     14
2      1      2      1
3      4      5     16
4     22     18     23
0    108    113    103
1    113    121    114
2    101    102    101
3    104    105    116
4    122    118    123

In [99]:
Data_Frame_5.columns = ["Deg_1", "Deg_2", "Farkli_Olan"] # Degisken Isimlerini Degistirdik

In [100]:
Data_Frame_5

Deg_1  Deg_2  Farkli_Olan
0      8     13            3
1     13     21           14
2      1      2            1
3      4      5           16
4     22     18           23

In [101]:
Data_Frame_6

Deg_1  Deg_2  Deg_3
0    108    113    103
1    113    121    114
2    101    102    101
3    104    105    116
4    122    118    123

In [102]:
# Simdi Yeinden Birlestirme Islemi Yapmayi Deneyelim

pd.concat([Data_Frame_5, Data_Frame_6]) # Degisken Isimleri Ayni Olmadigi Icin "NaN" Degeri Dondurdu ( PEKI BU SIKINTIYI NASIL COZUCEZ ?) (ASAGIYA BAK)

Deg_1  Deg_2  Farkli_Olan  Deg_3
0      8     13          3.0    NaN
1     13     21         14.0    NaN
2      1      2          1.0    NaN
3      4      5         16.0    NaN
4     22     18         23.0    NaN
0    108    113          NaN  103.0
1    113    121          NaN  114.0
2    101    102          NaN  101.0
3    104    105          NaN  116.0
4    122    118          NaN  123.0

In [103]:
pd.concat([Data_Frame_5, Data_Frame_6], join = "inner") # peki Bu        join = "inner"     Ifadesi Ne Yapti? --------->> Iki Ifadenin "Kesisimlerini" Aldi.

Deg_1  Deg_2
0      8     13
1     13     21
2      1      2
3      4      5
4     22     18
0    108    113
1    113    121
2    101    102
3    104    105
4    122    118

In [104]:
pd.concat([Data_Frame_5, Data_Frame_6], join = "inner", ignore_index = True) # Index nolari duzelticem

Deg_1  Deg_2
0      8     13
1     13     21
2      1      2
3      4      5
4     22     18
5    108    113
6    113    121
7    101    102
8    104    105
9    122    118

In [105]:
Data_Frame_5

Deg_1  Deg_2  Farkli_Olan
0      8     13            3
1     13     21           14
2      1      2            1
3      4      5           16
4     22     18           23

In [106]:
Data_Frame_6

Deg_1  Deg_2  Deg_3
0    108    113    103
1    113    121    114
2    101    102    101
3    104    105    116
4    122    118    123

In [107]:
# Birlestirme Isleminde Farkli Bir Islem Yapicaz Simdi

# pd.concat([Data_Frame_5, Data_Frame_6], join_axes = [Data_Frame_6.columns])

# join_axes IFADESINI BULAMADIGINI SOYLUYOR BOYLE BIR FONKSIYON YOK DIYOR, ADAM VIDEODA YAPIYO BURADA YAPAMADIM
# jupyter notebook ta da denedim calismadi

In [108]:
# Ileri Seviye Birlestirme Islemleri

In [109]:
df1 = pd.DataFrame({"Calisanlar": ["Ali", "Veli", "Ayse", "Fatma"],
                    "Grup": ["Muhasebe", "Muhendislik", "Muhendislik","Ik"]})

df1

Calisanlar         Grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           Ik

In [110]:
df2 = pd.DataFrame({"Calisanlar": ["Ali", "Veli", "Ayse", "Fatma"],
                    "Ilk_Giris": [2010, 2009, 2014, 2019]})

df2

Calisanlar  Ilk_Giris
0        Ali       2010
1       Veli       2009
2       Ayse       2014
3      Fatma       2019

In [111]:
pd.merge(df1, df2) # Merge Fonksiyonu Birlestirmelerin Hangi Degiskene Gore Yapilacagini Kendisi Anliyor Fakat Kendimiz Istersek Te Belirtebiliriz.

Calisanlar         Grup  Ilk_Giris
0        Ali     Muhasebe       2010
1       Veli  Muhendislik       2009
2       Ayse  Muhendislik       2014
3      Fatma           Ik       2019

In [112]:
pd.merge(df1, df2, on = "Calisanlar") # Calisanlar Uzerinde Birlestirme Yapmasini Soyledik

Calisanlar         Grup  Ilk_Giris
0        Ali     Muhasebe       2010
1       Veli  Muhendislik       2009
2       Ayse  Muhendislik       2014
3      Fatma           Ik       2019

In [113]:
df3 = pd.merge(df1, df2)

df3

Calisanlar         Grup  Ilk_Giris
0        Ali     Muhasebe       2010
1       Veli  Muhendislik       2009
2       Ayse  Muhendislik       2014
3      Fatma           Ik       2019

In [114]:
df4 = pd.DataFrame({"Grup": ["Muhasebe", "Muhendislik","Ik"],
                    "Mudur": ["Caner", "Mustafa", "Berkcan"]})

df4

Grup    Mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           Ik  Berkcan

In [115]:
# Coktan Teke Birlestirme Islemi

pd.merge(df3, df4)

Calisanlar         Grup  Ilk_Giris    Mudur
0        Ali     Muhasebe       2010    Caner
1       Veli  Muhendislik       2009  Mustafa
2       Ayse  Muhendislik       2014  Mustafa
3      Fatma           Ik       2019  Berkcan

In [116]:
# Coktan Coka Birlestirme Islemi

df5 = pd.DataFrame({'Grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

Grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [117]:
df1

Calisanlar         Grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           Ik

In [118]:
pd.merge(df1, df5) # !? Calisanlar kismi Coklulastirildi ama sikinti degilmis hoca oyle dedi

Calisanlar         Grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux