# ( Dikkat ) -- Makine Ogrenmesi Konularina Girmeye Basladik --

## Tahmine Dayalı Değer Atama Yöntemleri

In [1]:
import seaborn as sns
import missingno as msno
import pandas as pd
import numpy as np

In [2]:
df = sns.load_dataset("titanic")
df = df.select_dtypes(include = ["float64", "int64"])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

## Tahmine Dayalı Değer Atama - KNN & Random Forests & EM  ---->> ( KNN Yontemi )

In [3]:
!pip install ycimpute

In [4]:
# Ilgili Fonksiyonu Cagiriyoruz ---->>
# ---->> ( KNN Makine Ogrenmesi Kapsaminda Olan Bir Konudur Fakat ( Su Anlik ) Cok Detaylarina Girmeden Gorecegiz )

from ycimpute.imputer import knnimput

In [5]:
# Bu Kutuphaneyi Kullanmak Icin Oncelikle Degiskenlerin Isimlerini Tutmamiz Gerekiyor ( Bir Degiskene Atama Yapicaz )
# Bu Kutuphane Bizden Bir Numpy Array'i Bekliyor Dolayisi Ile Data_Framenin Isimlerini Bir Yerde Saklayip Daha Sonra Veri Setini
# Numpy Arrayine Ceviricez Atama Islemlerinden Sonra Tekrar Isimlerndirme Islemini Gerceklestiricez

In [6]:
var_names = list(df) # Isimleri Bir Yerde Sakliyoruz

In [7]:
var_names

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

In [8]:
n_df = np.array(df) # Data_Frame'yi Numpy Arrayine Cevirdik

In [9]:
n_df[0:10] # Numpy Arrayine Cevirdigimiz Icin ( .head() ) Fonksiyonunu Kullanamiyoruz

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [10]:
n_df.shape

(891, 6)

In [11]:
dff = knnimput.KNN(k = 4).complete(n_df) # k: Komsuluk Sayisini Ifade Eder, complete()  Doldur ( Neyi Doldurmak Istersin? ) -->>
# complete(n_df)  ---->>  Olusturmus Oldugumuz Numpy Array Nesnesini Doldur Demis Oluyoruz

# Su Anda Doldurma Islemini Gerceklestirdi ( Eksik Olarak Gormus Oldugu Gozlemleri Doldurdu )

Imputing row 1/891 with 0 missing, elapsed time: 0.125
Imputing row 101/891 with 0 missing, elapsed time: 0.126
Imputing row 201/891 with 0 missing, elapsed time: 0.127
Imputing row 301/891 with 1 missing, elapsed time: 0.127
Imputing row 401/891 with 0 missing, elapsed time: 0.128
Imputing row 501/891 with 0 missing, elapsed time: 0.129
Imputing row 601/891 with 0 missing, elapsed time: 0.129
Imputing row 701/891 with 0 missing, elapsed time: 0.130
Imputing row 801/891 with 0 missing, elapsed time: 0.130


In [12]:
type(dff) # Numpy Array'i Oldugunu Gormekteyiz

numpy.ndarray

In [13]:
# Bunu Pandas Data_Framesine Cevirmemiz Gerekiyor

dff = pd.DataFrame(dff, columns = var_names)

In [14]:
type(dff)

pandas.core.frame.DataFrame

In [15]:
dff.isnull().sum() # Eksik Deger Yok Cunku KNN Algoritmasi Ile Bu Gozlemleri Doldurduk

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

## Random Forests ( Yontemi )

In [16]:
# Dersler Arasinda Veri Seti Uzerinde Kalici Degisiklikler Yaptigimiz Icin Import Ediyorum

df = sns.load_dataset("titanic")
df = df.select_dtypes(include = ["float64", "int64"])

In [17]:
df.isnull().sum() # Eksiklikleri Gozlemliyoruz

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [18]:
var_names = list(df) # Isimleri Bir Yerde Sakliyoruz

In [19]:
var_names

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

In [20]:
n_df = np.array(df) # Data_Frame'yi Numpy Arrayine Cevirdik

In [21]:
# help(iterforest)

In [22]:
from ycimpute.imputer import iterforest

#dff = iterforest.IterImput().complete(n_df) # IterImput() Adinda Bir Modul Yokmus ( Ismi Degismis Olabilir ) ( !! Hata Var !! )

In [23]:
dff = pd.DataFrame(dff, columns = var_names) # ( Bilgilendirme ) ( "Hata" Oldugu Icin Islem Yapilamadi )

In [24]:
dff.isnull().sum() # ( Bilgilendirme ) ( "Hata" Oldugu Icin Islem Yapilamadi ) ( "dff" Bir Onceki Islemdeki Hali Gosteriliyor )

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

## EM Algoritmasi

In [25]:
# Dersler Arasinda Veri Seti Uzerinde Kalici Degisiklikler Yaptigimiz Icin Import Ediyorum

df = sns.load_dataset("titanic")
df = df.select_dtypes(include = ["float64", "int64"])

In [26]:
from ycimpute.imputer import EM

In [27]:
var_names = list(df) # Isimleri Bir Yerde Sakliyoruz

In [28]:
var_names

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

In [29]:
n_df = np.array(df) # Data_Frame'yi Numpy Arrayine Cevirdik

In [30]:
dff = EM().complete(n_df)

In [31]:
dff = pd.DataFrame(dff, columns = var_names)

In [32]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

In [33]:
# Genel Bilgilendirme; Bu Sekilde Tahmine Dayali Yontemleri Kullanmadan Once Yapisal Bir Bozukluk Varmi Diye Bakilir ---->>
# ---->> Diger Bir Deyis Ile Bazi Degiskenlerdeki Eksiklikler Acaba Diger Degiskenlere Bagli Olarak Mi Gerceklesiyo ---->>
# --->> Bunu Bir Gozlemlemek Gerekiyor ( Oneriliyor )

# Değişken Standardizasyonu (Veri Standardizasyonu)

In [34]:
# Degisken Standardizasyonu Ve Degisken Donusumu Arasindaki Farki Bilmek Onemlidir ( Ikiside Degiskenin Uzerinde Bi Donusturme Islemini Ifade Ediyo ) ( Peki Nedir Bu Ikisi Arasindaki Fark )

# Degisken Standardizasyonu Denildiginde Degiskenin Kendi Icindeki Varyans Yapisi Bilgi Yapisi Bozulmaz Fakat Belirli Bir Standarta Oturtulur Yani Bu Su Anlama Geliyor; Ornegin Degisken Oldugu Sekliyle Durdugunda 10 Diye Bir Deger Dusunelim
# Bu 10 Degeri Ornegin Veri Seti Kucukten Buyuge Dogru Siralandiginda 80. Sirada Bu Degisken Standartlastirildiginda Bu 10 Degeri Muhtemelen 1-2 Gibi Bir Deger Olucak Veya 0 Ile 1 Arasinda Bir Deger Olucak Fakat Veri Seti Yine Yucukten
# Buyuge Siralandiginda Bu Deger Yine 80. Degere Karsilik Geliyo Olucak Dolayisi Ile Bir Degisken Standartlastirildiginda Degiskenin Degerleri Degisecektir Belirli Bir Formata Sokulacaktir Fakat Tasimis Oldugu Yayilim Dagilim Bilgisinin
# Ozutu ( Direk Kendisi Degil ) Mevcutta Kaliyor Olucaktir Yani Degismeyecektir. Evet Degiskenin Tum Ortalama, Standart Sapma, Varyans Gibi Degerleri Degisecektir Ama Tasimis Oldugu Bilginin Degisken Icindeki Yayilimi Dagilimi Mevcut Durumu
# Degismeyecektir Bu Standartlastirma Islemidir

# Peki Degisken Donusturmek Ne Demektir?

# Degisken Donusturmek; Donusturulen Bir Degiskenin Tasidigi Bilginin Tasindigi Sekliyle Kalamamasi Donusturulmesi Demektir. Ornegin Cinsiyet Degiskenini Dusunelim ( Kadin - Erkek Seklinde ) Bunu Bir Donusturme Islemine Soktugumuzda
# Mesela 0 - 1 Dedigimizde Yapi Degismis Olucak ( Komple ) Yani Bir Standartalastirma Islemi Gibi Bir Islem Degil Veya Ornegin Elimizde Bir Yas Degiskeni Olsun Bu Yas Degiskenini Soyle Bir Degistirmek Istedigimizi Dusunelim 0-10 Arasi Cocuk
# Olarak Veya 1 Sinifi Olarak Degistir, 10-20 Yas Arasini Genc Olarak Degistir Gibi Bakin Degiskeni Donusturmek Istedigimizde Normalde Yasin Icerisinde Bulunan Degisim Yapisi Komple Bozuluyor Ve Mesela 0-80 Arasindaki Degerlerden Olusuyosa
# Bir Yas Degiskeni Bu Gunun Sonunda 1-2-3-4-5 Gibi Yada Cocuk, Yasli, Genc vb. Gibi Siniflara Ayrilmis Oluyor Buda Degiskeni Donusturmektir. Genelde Donusturme Islemleri Veri Setinin Tasidigi Bilginin Ozutunu Bozar Yada Amaclara Yonelik
# Olarak Onlari Numerik Olarak Ifade Etmek Gerekir Numerik Temsiller Yaratir. Cinsiyet Orneginde Oldugu Gibi Kadin-Erkek String Degerlerini Bazi Fonksiyonlarin Beklentilerinden Dolayi 0-1 Olarak Degistirir Aslinda Tasidigi Bilgi Bu Acidan
# Degismemis Olur Ama Yapisi Degismis Olur

# Simdi Degisken Standardizasyonu Orneklerine Gecelim

In [35]:
# Dersler Arasinda Veri Seti Uzerinde Kalici Degisiklikler Yaptigimiz Icin Import Ediyorum

# import numpy as np
# import pandas as pd
V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])
df = pd.DataFrame(
        {"V1" : V1,
         "V2" : V2,
         "V3" : V3})

df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

## Standardizasyon

In [36]:
from sklearn import preprocessing

In [37]:
preprocessing.scale(df) # .scale() ----->> Donustur Demektir ------>> Bu Tur Fonksiyonlarin Argumanlari Genelde Varsayilan Ayarlari ( copy = True, inplace = False ) Bu Sekildedir Yani Kalici Bir Degisiklik Yapmayiz Varsayilan Ayarlarda

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [38]:
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [39]:
df.mean()

V1    4.4
V2    7.8
V3    8.6
dtype: float64

## preprocessing.normalize(df)Normalizasyon

In [40]:
# Normalizasyon Islemi Degerleri 0 Ile 1 Arasina Donusturmek Icin Kullanilir

preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min-Max Dönüşümü

In [41]:
# Istemis Oldugumuz Iki Tane ( Deger )Araligin Arasina Degerleri Donusturmek Istersek Bu Yontem Kullanilir

scaler = preprocessing.MinMaxScaler(feature_range = (100,200)) # Simdi Bunu Bir Nesne Olarak Olusturdu ( Assagidaki Kisimda Da Goruntuleyebiliyoruz ) ( Bu Bir Donusturme Islemidir )

In [42]:
scaler.fit_transform(df)

array([[100.        , 128.57142857, 111.11111111],
       [133.33333333, 128.57142857, 177.77777778],
       [183.33333333, 100.        , 100.        ],
       [166.66666667, 142.85714286, 111.11111111],
       [200.        , 200.        , 200.        ]])

In [43]:
# Baska Bir Ornek;

scaler = preprocessing.MinMaxScaler(feature_range = (10,20)) # Araligi Degistirdim

In [44]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

## Değişken Dönüşümleri

In [45]:
# Herbir Stardardizasyon Zaten Degisken Donusumudur ( Hepsi Bir Donusum Islemi Gibi Dusunulmelidir ) ( Onemli olan Mevzu Mevcut Degiskenin Tasidigi Bilginin Yapisini Bozuyomuyuz?  -  Bozmuyomuyuz? ) ( Bunu Goz Onunde Bulundurmak Lazim )

In [46]:
# Veri Setimizi Import Ettik

df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### 0-1 Dönüşümü

In [47]:
# Burada Dikkat Edilmesi Gereken Bir Mevzu Var; Hangisine 0 Hangisine 1 Dedigimizi Iyi Bilmemiz Gerekiyor

In [48]:
# Ornegin Cinsiyet Degiskenini 0-1 Olarak Donusturucez ( Dunyadaki En Cok Kullanilan Donusum Islemi )

from sklearn.preprocessing import LabelEncoder

lbe = LabelEncoder() # bir Nesne Olusturuyoruz ( Bunu Bir Donusturucu Gibi Dusunebiliriz )

In [49]:
lbe.fit_transform(df["sex"]) # Veri Setinin Original Halinde Degisme Yoktur ( Assagida Gorulebilir )

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [50]:
df # Degisim Yok Oldugu Gozlenebilir

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [51]:
df["yeni_sex"] = lbe.fit_transform(df["sex"]) # Yeni Bir Degiskene Atayabiliriz ( Tavsiye Edilir )

In [52]:
df # Yeni Halini Burada Gorebiliriz

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

### "1 ve Diğerleri (0) " Dönüşümü

In [53]:
# "time" yada "day" degiskenleri Icin Kullanilabilir

In [54]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [55]:
df["day"].str.contains("Sun")

0       True
1       True
2       True
3       True
4       True
       ...  
239    False
240    False
241    False
242    False
243    False
Name: day, Length: 244, dtype: bool

In [56]:
# import numpy as np

# np.where ---->> Bir Kosul Calistirmak Icin Kullanacak Oldugumuz Fonksiyon
# df["day"].str ----->> df in Icerisindeki day Degiskenini String Degeri Olarak Degerlendir
# contains("Sun") ------->> Eger Bu String Ifadenin Icerisinde "Sun" ( Sunday ) Ifadesi Varsa 1 De, Digerlerine 0 De ------>> contains ----->> ( Sorgulama Icin Kullanilir )

df["yeni_day"] = np.where(df["day"].str.contains("Sun"), 1, 0)

In [57]:
df # Buradaki Sun ( Sunday ) Olan Degerlerin Hepsine 1 Degeri Koymus Onun Disindaki Turm Degerlere 0 Degeri Koymus

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

### Çok Sınıflı Dönüşüm

In [58]:
# Digerlerinde Oldugu Gibi Bir Kategorik Degiskenin Siniflari Sayilara Donusturulur

from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [59]:
lbe.fit_transform(df["day"]) # 0 Dan Baslayacak Sekilde Kac Tane Sinif Varsa Ona Gore Numaralandirma Yapti

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [60]:
#cok dikkat 

In [61]:
# Simdi çok DIKKAT eğer elinizdeki kategorik değişkenin ikiden fazla sınıfı varsa ve fonksiyonların bizden beklentisi doğrultusunda bu kategorik degiskeni Bu Sekilde nümerik bir formata çevirmek istiyorsak ve neticesinde Bu Sekilde 
# Cevirme Islemi Yaptiysak
# Burasi Cok hassas Bir Nokta 
# çünkü eğer elimizdeki bir değişkenin bu şekilde bir numerik değerleri dönüştürürde Bu Sekilde algoritmalara gönderirsek bu artık bunu sıfırla 3 arasındaki değerlerden oluşan bir değişken olarak tanımlayacak yani aslına bakarsanız
# bu dönüşüm algoritmaların kafasını karıştıracak de kategorik değişkenler sınıflarının bağımlı değişkeni olan etkileri bozulacaktır neden bozulmaktadır çünkü burada sınıflar numerik değerleri dönüştü işte bazıları bir bazıları üç vs
# şeklinde yani normalde Bir Kategorik Degiskenin Nominal Ölçek türü ile ölçülmüş olan durumu yani sınıflar arasındaki mesafesi eşit olan durumu bir anda Bi Donusum Islemi Ile bozulup sanki aralarında fark varmışçasına bir sıralama
# işlemine Tutulmuş oldu Bakin Tekrar Altini Ciziyorum Bir Kategorik Degiskenin 4-5-6-10 sınıfı olduğunu düşünelim sınıfların arası eşitti hatırlayın Verş okuryazarlığı bölümlerinden şimdi biz bunu böyle bir dönüşme tabi tuttuğumuz da
# bu yapıyı bozuyoruz Değilmi? mesela 0 Ile 10 arası olsun Degerler 0 dan 10'a doğru gittikçe sanki bu değerler artıyormuş gibi gözüküyor yani 8 daha büyükmüş gibi gözüküyor halbuki bu nominal Olcek Turu Ile Olculmus bir kategorik
# degiskendi işte bu sebeple bu tip çok sınıflı kategorik değişkenleri fonksiyonların beklentileri ya da işimiz doğrultusunda bir dönüştürme işlemine nümerik Olarak soktuğumuzda bu bir çok probleme sebep olabilmektedir yanlılıklara
# ve hatalı çıkarımlara,gürültüye sebep olabilmektedir ve algoritmaları şaşırtmaktadır aldatmaktadır peki bu durumda ne yapacağız bu durumda "One-Hot encoding" yani "One-Hot dönüşümü" yapmış olacağız

### One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [62]:
# !! Soo Important !!

# En Onemli Konulardan Birisi

In [63]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0       16.99  1.01  Female     No  Sun  Dinner     2         0         1
1       10.34  1.66    Male     No  Sun  Dinner     3         1         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0         1

In [64]:
df_one_hot = pd.get_dummies(df, columns = ["sex"], prefix = ["sex"]) # prefix ----->> yapilacak Olan ( Olusturulacak Olan ) Degiskenlerin On Isimlendirmesinin Ne Olacagini Ifade Etmek Demek

In [65]:
df_one_hot.head() # ( Gorulecegi Uzere Yukaridaki Islemde Ne Oldu ) Burada Ne Oldu; Elimizdeki Iki Sinifli Kategorik Degiskenin Sinif Sayisi Kadar Yeni Degisken Olustu Ve Olusmus Olan Bu Yeni Degiskenlerde 1 - 0 Olarak Tanimlanmis Oldu

total_bill   tip smoker  day    time  size  yeni_sex  yeni_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2         0         1         0   
1       10.34  1.66     No  Sun  Dinner     3         1         1         1   
2       21.01  3.50     No  Sun  Dinner     3         1         1         1   
3       23.68  3.31     No  Sun  Dinner     2         1         1         1   
4       24.59  3.61     No  Sun  Dinner     4         0         1         0   

   sex_Female  
0           1  
1           0  
2           0  
3           0  
4           1

In [66]:
# !! Soo Important !!

# Dami Degisken Tuzagi; Bir Degiskeni Ifade Eden Baska Bir Degisken Varsa ( Yukarida ki "sex_Male" Veya "sex_Female" Ifadeleri Aslinda Ayni Bilgiyi Tasimaktadir Yani Bu Duruma Uyuyor ) 

# Peki Bu Durumu Nasil Kontrol Altinda Tutabiliriz; Olusturulan Degisken Sayisindan Bir Az Sayida Daha Dogru Ifadesi Ile Kategorik Degiskenin Sinif Sayisindan Daha Az Sayida Dami Degiskeni Olmasi Gerekiyor

# Ornegin Yukarida Cinsiyetin Iki Tane Sinifi Vardi, Bu Durumda 1 Tane Dami Degiskeni Olmasi Lazim ------->> Degiskenin Original Halinde Veri Setinde Olmamali

In [67]:
# Daha Fazla Sinifa Sahip Bir Degisken Ornegi Yapalim

pd.get_dummies(df, columns = ["day"], prefix = ["day"]).head()

total_bill   tip     sex smoker    time  size  yeni_sex  yeni_day  \
0       16.99  1.01  Female     No  Dinner     2         0         1   
1       10.34  1.66    Male     No  Dinner     3         1         1   
2       21.01  3.50    Male     No  Dinner     3         1         1   
3       23.68  3.31    Male     No  Dinner     2         1         1   
4       24.59  3.61  Female     No  Dinner     4         0         1   

   day_Thur  day_Fri  day_Sat  day_Sun  
0         0        0        0        1  
1         0        0        0        1  
2         0        0        0        1  
3         0        0        0        1  
4         0        0        0        1

In [68]:
# Yani Ozetle One-Hot Donusumunun Bize Iki Faydasi Var
# 1. Si; Genelde Numerik Degerlere Donusturerek Algoritmalari Kullaniyoruz Buradaki Numerik Donusturme Islemini Gerceklestirmis Oluyor
# 2. Si; Kategorik Degiskenlerin Icerisindeki Siniflarin Etkisini Veri Setinde Hissedilir Bir Hale Donusturmemize Yardimci Oluyor

In [69]:
# *-*-*-* Machine Learning Baslangic Yeri *-*-*-*