In [1]:
# SATIR 1 , SUTUN 0 DIYE BILIYORUM( bakilmasi lazim )

In [2]:
import numpy as np

print(np.random.randint(10, size = 7)) # 0 dan 10 a kadar 7 tane sayi yazdirdik.

[7 5 1 5 1 6 1]


In [3]:
a = np.random.randint(10, size = 7) # Tek Boyutlu

b = np.random.randint(10, size = (3,5)) # 2 Boyutlu

In [4]:
# BOYUT SAYISI

print("a : ", a.ndim)

print("b : ", b.ndim)

a :  1
b :  2


In [5]:
# BOYUT BILGISI

print("a : ", a.shape) # Tek Boyut Var ve Icinde 7 Tane Eleman Var Oldugu Gozukmustur.

print("b : ", b.shape)

a :  (7,)
b :  (3, 5)


In [6]:
# Icerisinde ki Toplam Eleman Sayisini Bize Verir.

print("a : ", a.size)

print("b : ", b.size)

a :  7
b :  15


In [7]:
print(a.dtype) # Icerisindeki Verilerin Veri Tipini Bize Verir.

print(b.dtype)

int64
int64


In [8]:
# Bir Array i Yeniden Boyutlandirmak Istersek ".reshape" kullanilir.

c = np.random.randint(7, size = 9, dtype = int)

print("c : ", c)

print()

print("3x3 matris hali : \n\n",c.reshape(3,3))

c :  [1 6 1 0 2 5 3 2 5]

3x3 matris hali : 

 [[1 6 1]
 [0 2 5]
 [3 2 5]]


In [9]:
# IKI FARKLI ARRAY I BIR ARAYA GETIRME

# BIRLESTIRME

d = np.array([1,2,3])
e = np.array([4,5,6])

f = np.concatenate([d,e]) # Birlestirme Islemi

print("f : ", f)

f :  [1 2 3 4 5 6]


In [10]:
# Ekleme Islemini Istegimiz Dogrultusunda Yeniden Yapabiliyoruz.

g = np.array([7,8,9])

h = np.concatenate([f,g])

print(h)

# ---------------------------------------------------------------

print("-------------------")

# bir baska sekilde ekleme yapicam

i = np.concatenate([d,e,g])

print(i)

[1 2 3 4 5 6 7 8 9]
-------------------
[1 2 3 4 5 6 7 8 9]


In [11]:
# IKI BOYUTTA BIRLESTIRME ISLEMI

j = np.array([[1,2,3],
              [4,5,6]]) # Okunabilirlik Acisindan Alt Satira Indim

k = np.concatenate([j,j])

print(k) # BU BIRLESTIRME ISLEMI SATIR BAZINDADIR

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [12]:
L = np.concatenate([j,j] , axis = 0) # Aslinda Bu Zamana Kadar Yaptigimiz Sey Bu Ifadeydi Eksen Ile Belirtildiginde 0 Dememiz Lazim.

In [13]:
# SUTUN BAZINDA BIRLESTIRME ISLEMI - m ifadesi

m = np.concatenate([j,j] , axis = 1) 

print(L)

print("---------")

print(m)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
---------
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [14]:
# AYIRMA ISLEMI

n = np.array([1,2,3,4,5,6,7,8,9])

print(np.split(n, [3,5])) # n adindaki array i 3'e Kadar Ve 5'e Kadar Bol demektir.

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


In [15]:
# Yukarida ki Ifade de 3 tane ayri Bolum Var Bu Ifadeleri Atama Yapicaz.

o,p,r = np.split(n, [3,5])
print(o)
print(p)
print(r)

[1 2 3]
[4 5]
[6 7 8 9]


In [16]:
# 2 BOYUTLU AYIRMA ISLEMLERI

s = np.arange(16).reshape(4,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
# YATAY BOLME ISLEMI YAPILMISTIR.

print(np.vsplit(s, [2]))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [18]:
# DIKEY BOLME ISLEMI YAPILMISTIR.

print(np.hsplit(s, [2]))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [19]:
# BIR BOYUTTA SIRALAMA ISLEMLERI
# :!

t = np.array([8,5,7,9,4,1,6])

print(np.sort(t))

print("---------------")

print(t) # Original Hali Sirali Degildir.

t.sort() # Original Halini Siraya Aldik

print("---------------")

print(t) # Original Hali Siralidir.

[1 4 5 6 7 8 9]
---------------
[8 5 7 9 4 1 6]
---------------
[1 4 5 6 7 8 9]


In [20]:
# IKI BOYUTTA SIRALAMA ISLEMLERI

u = np.random.normal(14, 5, (3,3))

print(u)

print("\n*****************************************\n")
print("Satirlari Kucukten Buyuge Siralama")
print("-----------------------------------\n")

print(np.sort(u, axis = 1))

print("\n\n*****************************************\n")
print("Sutunlari Kucukten Buyuge Siralama")
print("-----------------------------------\n")
print(np.sort(u, axis = 0))

[[ 8.32234781 19.29113888 16.69334692]
 [12.23622512 12.78034394  9.91263014]
 [13.88603811 13.64357836 22.33853763]]

*****************************************

Satirlari Kucukten Buyuge Siralama
-----------------------------------

[[ 8.32234781 16.69334692 19.29113888]
 [ 9.91263014 12.23622512 12.78034394]
 [13.64357836 13.88603811 22.33853763]]


*****************************************

Sutunlari Kucukten Buyuge Siralama
-----------------------------------

[[ 8.32234781 12.78034394  9.91263014]
 [12.23622512 13.64357836 16.69334692]
 [13.88603811 19.29113888 22.33853763]]
