In [1]:
import numpy as np

a = np.arange(1,11) # Aralik Belitiyoruz Sonra Yazdiriyoruz Hepsini.

print(a)

print(a[5])

[ 1  2  3  4  5  6  7  8  9 10]
6


In [2]:
b = np.random.randint(1,10,size = (3,5))

print(b)

[[4 2 1 2 9]
 [8 4 7 4 1]
 [3 1 3 1 2]]


In [3]:
print("\nListe Icerisindeki Elemanlara Ulasmak : ",b[0,0])
print("\nListe Icerisindeki Elemanlara Ulasmak : ",b[0,1])
print("\nListe Icerisindeki Elemanlara Ulasmak : ",b[2,2])


Liste Icerisindeki Elemanlara Ulasmak :  4

Liste Icerisindeki Elemanlara Ulasmak :  2

Liste Icerisindeki Elemanlara Ulasmak :  3


In [4]:
c = np.random.randint(1,11,(5,5))

print(c)

[[ 1  9  7  5  2]
 [ 1  6  8  9  1]
 [10  9  1  6 10]
 [ 9  6  8  1  5]
 [ 3  3  1  3  9]]


In [5]:
# Iki Boyutlu Matrislerde Elemanlara Toplu Olarak Ulasmak

print(c[:,0]) # 1. Sutun Aldik

print("\n**************\n")
print(c[1:3 , 1:]) # 2 Boyutta secili Olan Yerleri Aldik --- 1,2. indexteki satirlari al dedik sonra 1. indexteki sutunlari al dedik ve kesistigi yerleri aldik

[ 1  1 10  9  3]

**************

[[ 6  8  9  1]
 [ 9  1  6 10]]


In [6]:
d = np.random.randint(1,10,(6,6))

print(d)

[[7 7 7 4 6 5]
 [9 5 6 6 5 5]
 [1 4 8 6 3 1]
 [5 5 4 4 8 7]
 [1 4 3 1 4 7]
 [3 9 7 5 2 4]]


In [7]:
# -- Soo Important -- 

e = d[1:5 , 2:6] # Burada Yapilan Ifade bir nevi Soyle Dusunulebilir, "REFERANS ALINIYOR" , e Degiskenini Olusturabilmek Icin d Uzerinden Referans aldik 

# PEKI BU NE ANLAMA GELIYOR;

# "e" Degiskeninin Uzerinde Yapilan Herhangi Bir Degisiklik "d" Uzerinde de Yapilmis Sayilacaktir Cunku Referans Aldigi Yer "d" Degiskenidir.

# PEKI "e" de Yapilan Bir Islemin Nasil "d" Degiskeni Uzerinde Degisiklik Yapmamasini Saglayabiliriz ?

# "d" Degiskeni ni "e" degiskeni Uzerine Koyapalayarak Orn:    e = d.copy()     Bu Ifadeyi Aralik Vererek Te Yapabiliriz Yukaridaki Orneklerde Yaptigimiz Gibi

# Simdi Bir Uygulama Yapalim :)

print(e)

[[6 6 5 5]
 [8 6 3 1]
 [4 4 8 7]
 [3 1 4 7]]


In [8]:
K = np.random.randint(1,11,(5,5))

print(K)

[[ 3  7  3  7 10]
 [ 9  8  3  4  2]
 [ 8  6  7  4  3]
 [ 4  8  2  5 10]
 [ 6  7  1  7  7]]


In [9]:
L = K[1:3 , 0:3]

print(L)

# Simdi "L" Uzerinde Yapilan Bir Degisiklik "K" Da da Degisiklige Neden Olur. 

[[9 8 3]
 [8 6 7]]


In [10]:
M = K[1:3 , 0:3].copy() # Burada Yapilan Yani "M" Uzerinde Yapilan Bir Degisiklik "K" Uzerinde Bir Degisiklige Neden Olmaz.

print(M)

[[9 8 3]
 [8 6 7]]


In [11]:
# Goruldugu Uzere "M" Uzerinde Yapilan Bir Degisiklik "K" yi Etkilememistir.

M[0,0] = 10

print(M)

print("\n*********\n")

print(K)

[[10  8  3]
 [ 8  6  7]]

*********

[[ 3  7  3  7 10]
 [ 9  8  3  4  2]
 [ 8  6  7  4  3]
 [ 4  8  2  5 10]
 [ 6  7  1  7  7]]


In [12]:
# --- Soo Important ---

# *** Fancy Index Ile Elemanlara Ulasmak *** (Tek Boyutta)

U = np.random.randint(1, 11, 10)

print(U)

[10  7  9  8  5  4  6  9  5  4]


In [13]:
# Normal Sartlarda Bu Sekilde Index No'suna Gore Ulasabiliyorduk

V = [U[1], U[3], U[5]]

print(V)

[7, 8, 4]


In [14]:
# !!! Soo Important !!!

# BU YONTEM ILE DE ULASILABILIR.

# FANCY INDEX METHOD ILE INDEX ELEMANLARINA ULASMAK ( ILERI SEVIYE BIR KONUDUR. )

Y = [1,3,5]

print(U[Y])

[7 8 4]


In [15]:
Z = np.arange(25).reshape((5,5))

print(Z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
# 2 Boyutlu Bir Dizide Fancy Index Kullanmak

Satir = np.array([1,3])

Sutun = np.array([2,2])

print(Z[Satir , Sutun])

[ 7 17]


In [17]:
# Basit Index Ile Fancy Index (Bir Arada) Kullanimi

print(Z)

print("\n***************\n")

print(Z[0 , [1,2]])

print("\n***************\n")

print(Z[1 , [2,4]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

***************

[1 2]

***************

[7 9]


In [18]:
# Slice Ile Fancy Index (Bir Arada) Kullanimi
# Slice : Belirli Bir Aralik Aliyorduk Ya mesela -----> [0:3] , [:5] Gibi


print(Z[0: , [2,4]]) # 2. ve 4. Sutundaki Elemanlarin Hepsini Yazdirdik.

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


In [19]:
# Kosullu Eleman Islemleri

N = np.array([1,2,3,4,5,6])

print(N<4) # Burada Ki Islemde N array inin Icindeki Elemanlar 4 ten Kucuk Mudur Diye Sorguladik.

print("\n*************************************\n")

print(N[N<4]) # Burada Ki Islemde N array inin Icindeki 4 ten Kucuk Olan Elemanlari Yazdirmasini Yaptik.    -------> DIKKAT : ASLINDA BURADA FANCY KULLANIYORUZ

# !? Yukarida Yapilan Islem Butun Mantik Operatorleri Icin Gecerlidir.

[ True  True  True False False False]

*************************************

[1 2 3]


In [20]:
# Vektorel Islemler

print(N * 5)

print("\n*******************\n")

print(N / 5)

print("\n*******************\n")

print(N / 5 * 7) # Gibi Matematiksel Islemlere De Sokabiliriz Vektorleri

[ 5 10 15 20 25 30]

*******************

[0.2 0.4 0.6 0.8 1.  1.2]

*******************

[1.4 2.8 4.2 5.6 7.  8.4]


In [21]:
# --- Matematiksel Islemler ---

# Yaptigimiz Matematiksel Islemleri Aslinda Bir Bir Yontem Kullanarak Yapabilmekteyiz. ( ufunc )

print("Array'imiz : ",N) # Array'imiz

print("\n-------------\n")

print(np.subtract(N, 1)) # 1 Eksiltme

print("\n*************")

print(np.add(N, 1)) # 1 ekleme

print("\n*************")

print(np.multiply(N,4)) # 4 Ile Carpma

print("\n*************")

print(np.divide(N, 3)) # 3 e Bolme

print("\n*************")

print(np.power(N, 3)) # Kup alma

print("\n*************")

print(np.mod(N, 2)) # Mod Alma

print("\n*************")

print(np.absolute(np.array([-3]))) # Mutlak Deger

Array'imiz :  [1 2 3 4 5 6]

-------------

[0 1 2 3 4 5]

*************
[2 3 4 5 6 7]

*************
[ 4  8 12 16 20 24]

*************
[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.        ]

*************
[  1   8  27  64 125 216]

*************
[1 0 1 0 1 0]

*************
[3]


In [22]:
# Trigonometrik Degerleri de Bu Kutuphane Sayesinde Kullanabiliriz.

print(np.sin(360))
print(np.cos(180))

0.9589157234143065
-0.5984600690578581


In [23]:
# Logaritmik Ifade De Kullanabiliriz

print(np.log(np.array([1,2,3]))) # array Icerisindeki Tum Elemanlarin Logaritmasini Aldik

print(np.log2(np.array([1,2,3]))) # array Icerisindeki Tum Elemanlarin Logaritmasini Aldik  ----->  # derecesini ( taban degerini ) de ayarlayabiliriz

print(np.log10(np.array([1,2,10]))) # array Icerisindeki Tum Elemanlarin Logaritmasini Aldik  ----->  # derecesini ( taban degerini ) de ayarlayabiliriz

[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.      0.30103 1.     ]


In [24]:
# !!! SOO IMPORTANT !!!

# cheatsheet Kavrami ----> Herhangi Bir Ifade Ogrenmek Istiyorsak mesala NumPy Kutuphanesinin Fonksiyonlarini fln Ogrenmek Istiyorum
# google ye yazarsak "NumPy Cheatsheet" diye O konu Ile Ilgili Ifadeler Karsimiza gelir.

In [25]:
# 2 Bilinmeyenli 2 Denklem Cozumu

"""

5 * x0 + x1 = 15
x0 + 7 * x1 = 37

"""

# denklemimizdir

'\n\n5 * x0 + x1 = 15\nx0 + 7 * x1 = 37\n\n'

In [26]:
x1 = np.array([[5,1] , [1,7]])
x2 = np.array([15,37])

Kokler = np.linalg.solve(x1,x2)

print(Kokler) # koklerimiz :   x1 = 2   ve   x2 = 5   tir.

[2. 5.]
